import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Header } from "@/components/header";
import { TanStackQueryProvider } from "@/providers/tan-stack-query-provider";
import { Toaster } from "@/components/ui/sonner";
import { ReactScan } from "@/components/react-scan";
import { NuqsAdapter } from "nuqs/adapters/next/app";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "TanStack React Query Examples",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <ReactScan />
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <NuqsAdapter>
                    <TanStackQueryProvider>
                        <ThemeProvider
                            attribute="class"
                            defaultTheme="system"
                            enableSystem
                            disableTransitionOnChange
                        >
                            <Header />
                            {children}
                            <Toaster richColors closeButton />
                        </ThemeProvider>
                    </TanStackQueryProvider>
                </NuqsAdapter>
            </body>
        </html>
    );
}
